spring:
  profiles:
    active: dev
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-user
              uri: http://localhost:8082
              predicates:
                - Path=/user/**,/admin/**
              filters:
                - RewritePath=/user/v3/api-docs(?<segment>/.*)?, /v3/api-docs${segment}

            - id: ms-payment
              uri: http://localhost:8083
              predicates:
                - Path=/payments/**,/pay/**
              filters:
                - RewritePath=/payments/v3/api-docs(?<segment>/.*)?, /v3/api-docs${segment}

            - id: ms-auth
              uri: http://localhost:8085
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/v3/api-docs(?<segment>/.*)?, /v3/api-docs${segment}

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key:

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: ms-user
        url: /user/v3/api-docs
      - name: ms-payment
        url: /payments/v3/api-docs
      - name: ms-auth
        url: /auth/v3/api-docs
    urls-primary-name: ms-user
    display-request-duration: true
    operations-sorter: method
  api-docs:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
